procedure Main is

begin

   --GENERAR LA CLASE MOVIL CON LOS SIGUIENTES ATRIBUTOS
   --POSICION X, POSICION Y, VELOCIDAD X, VELOCIDAD Y
   --DEFINIDA A LA HORA DE INSTANCIAR UN OBJETO
   --AGREGAR UN MÉTODO TO_STRING QUE MUESTRA LA POSICION ACTUAL DEL MOVIL
   --METODO ACTUALIZAR QUE RECIBE UN DELTTA DE UN TIEMPO Y ACTUALIZA LA POSICION DEL MOVIL
end Main;
