procedure Main is

begin
   --CREAR UN PAQUETE
   --CLASE ABSTRACTA FIGURA CON METODO ABSTRACTO AREA
   --HEREDAN EL CUADRADO, EL TRIANGULO Y EL CIRCULO
   --EL CUADRADO TIENE BASE Y ALTURA
   --EL CIRCULO TIENE RADIO
   --GETTTERS Y CONSTRUCTORES
   --LAS SUBCLASES IMPLEMENTAN METODO AREA (CALCULARLA BASICAMENTE)
   --EN EL MAIN UN VECTOR(ARRAYLIST) DE FIGURAS DE FORMA ALEATORIA QUE TENGA CIRCULOS Y CUADRADOS
   --CALCULAR CON TAMAÑO TAMBIEN ALEATORIO
   --MOSTRAR SUMATORIA DEL AREA DE TODAS LAS FIGURAS UNA VEZ CARGADO EL ARRAY
   null;
end Main;
